language: r

matrix:
  include:
    - r: oldrel
      os: linux
    - r: release
      os: linux
    - r: devel
      os: linux
    - r: release
      os: osx

warnings_are_errors: true

env:
  global:
    - RCEREAL_TEST_GITHUB=TRUE
    - RCEREAL_TEST_UPDATE=TRUE
    - RCEREAL_TEST_MYCLASS=TRUE
